a = ord('B')
b = ord('C')
c = ord('D')
d = ord('c')
e = ord('d')
f = ord('0')
g = ord('1')
h = ord('2')
i = ord('$')
j = ord('+')
print(a, " ", b, " ", c, " ", d, " ", e, " ", f, " ", g, " ", h, " ", i, "", j)
