print("Integer equivalent for 'A': ", ord('A'))
print("Integer equivalent for 'B': ", ord('B'))
print("Integer equivalent for 'C': ", ord('C'))
print("Integer equivalent for 'b': ", ord('b'))
print("Integer equivalent for 'c': ", ord('c'))
print("Integer equivalent for 'd': ", ord('d'))
print("Integer equivalent for '0': ", ord('0'))
print("Integer equivalent for '1': ", ord('1'))
print("Integer equivalent for '2': ", ord('2'))
print("Integer equivalent for '$': ", ord('$'))
print("Integer equivalent for '*': ", ord('*'))
print("Integer equivalent for '+': ", ord('+'))
print("Integer equivalent for ' ': ", ord(' '))
