int_equivalent = ord('B')
print("The integer equivalent of B is", int_equivalent)
int_equivalent = ord('C')
print("The integer Equivalent of C is", int_equivalent)
int_equivalent = ord('D')
print("The integer Equivalent of D is", int_equivalent)
int_equivalent = ord('i')
print("The integer Equivalent of i is", int_equivalent)
int_equivalent = ord('c')
print("The integer Equivalent of c is", int_equivalent)
int_equivalent = ord('d')
print("The integer Equivalent of d is", int_equivalent)
int_equivalent = ord('0')
print("The integer Equivalent of 0 is", int_equivalent)
int_equivalent = ord('1')
print("The integer Equivalent of 1 is", int_equivalent)
int_equivalent = ord('2')
print("The integer Equivalent of 2 is", int_equivalent)
int_equivalent = ord('$')
print("The integer Equivalent of $ is", int_equivalent)
int_equivalent = ord('*')
print("The integer Equivalent of * is", int_equivalent)
int_equivalent = ord('+')
print("The integer Equivalent of + is", int_equivalent)
int_equivalent = ord(' ')
print("The integer Equivalent of space character is", int_equivalent)