print(ord('A'))
print(ord('B'))
print(ord('C'))
print(ord('D'))
print(ord('i'))
print(ord('c'))
print(ord('d'))
print(ord('0'))
print(ord('1'))
print(ord('2'))
print(ord('$'))
print(ord('*'))
print(ord('+'))
print(ord(' '))