from re import I


data = [
    {
        "login": "gentlesolo",
        "id": 5492998,
        "node_id": "MDQ6VXNlcjU0OTI5OTg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/5492998?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gentlesolo",
        "html_url": "https://github.com/gentlesolo",
        "followers_url": "https://api.github.com/users/gentlesolo/followers",
        "following_url": "https://api.github.com/users/gentlesolo/following{/other_user}",
        "gists_url": "https://api.github.com/users/gentlesolo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gentlesolo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gentlesolo/subscriptions",
        "organizations_url": "https://api.github.com/users/gentlesolo/orgs",
        "repos_url": "https://api.github.com/users/gentlesolo/repos",
        "events_url": "https://api.github.com/users/gentlesolo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gentlesolo/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "daunikman",
        "id": 8968140,
        "node_id": "MDQ6VXNlcjg5NjgxNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8968140?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/daunikman",
        "html_url": "https://github.com/daunikman",
        "followers_url": "https://api.github.com/users/daunikman/followers",
        "following_url": "https://api.github.com/users/daunikman/following{/other_user}",
        "gists_url": "https://api.github.com/users/daunikman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/daunikman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/daunikman/subscriptions",
        "organizations_url": "https://api.github.com/users/daunikman/orgs",
        "repos_url": "https://api.github.com/users/daunikman/repos",
        "events_url": "https://api.github.com/users/daunikman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/daunikman/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "ehizman",
        "id": 23247186,
        "node_id": "MDQ6VXNlcjIzMjQ3MTg2",
        "avatar_url": "https://avatars.githubusercontent.com/u/23247186?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ehizman",
        "html_url": "https://github.com/ehizman",
        "followers_url": "https://api.github.com/users/ehizman/followers",
        "following_url": "https://api.github.com/users/ehizman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ehizman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ehizman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ehizman/subscriptions",
        "organizations_url": "https://api.github.com/users/ehizman/orgs",
        "repos_url": "https://api.github.com/users/ehizman/repos",
        "events_url": "https://api.github.com/users/ehizman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ehizman/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "Olaoluolowe",
        "id": 24969588,
        "node_id": "MDQ6VXNlcjI0OTY5NTg4",
        "avatar_url": "https://avatars.githubusercontent.com/u/24969588?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Olaoluolowe",
        "html_url": "https://github.com/Olaoluolowe",
        "followers_url": "https://api.github.com/users/Olaoluolowe/followers",
        "following_url": "https://api.github.com/users/Olaoluolowe/following{/other_user}",
        "gists_url": "https://api.github.com/users/Olaoluolowe/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Olaoluolowe/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Olaoluolowe/subscriptions",
        "organizations_url": "https://api.github.com/users/Olaoluolowe/orgs",
        "repos_url": "https://api.github.com/users/Olaoluolowe/repos",
        "events_url": "https://api.github.com/users/Olaoluolowe/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Olaoluolowe/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "hedreez09",
        "id": 29062895,
        "node_id": "MDQ6VXNlcjI5MDYyODk1",
        "avatar_url": "https://avatars.githubusercontent.com/u/29062895?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hedreez09",
        "html_url": "https://github.com/hedreez09",
        "followers_url": "https://api.github.com/users/hedreez09/followers",
        "following_url": "https://api.github.com/users/hedreez09/following{/other_user}",
        "gists_url": "https://api.github.com/users/hedreez09/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/hedreez09/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/hedreez09/subscriptions",
        "organizations_url": "https://api.github.com/users/hedreez09/orgs",
        "repos_url": "https://api.github.com/users/hedreez09/repos",
        "events_url": "https://api.github.com/users/hedreez09/events{/privacy}",
        "received_events_url": "https://api.github.com/users/hedreez09/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "solutionCraftsman",
        "id": 29656757,
        "node_id": "MDQ6VXNlcjI5NjU2NzU3",
        "avatar_url": "https://avatars.githubusercontent.com/u/29656757?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/solutionCraftsman",
        "html_url": "https://github.com/solutionCraftsman",
        "followers_url": "https://api.github.com/users/solutionCraftsman/followers",
        "following_url": "https://api.github.com/users/solutionCraftsman/following{/other_user}",
        "gists_url": "https://api.github.com/users/solutionCraftsman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/solutionCraftsman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/solutionCraftsman/subscriptions",
        "organizations_url": "https://api.github.com/users/solutionCraftsman/orgs",
        "repos_url": "https://api.github.com/users/solutionCraftsman/repos",
        "events_url": "https://api.github.com/users/solutionCraftsman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/solutionCraftsman/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "CaptainBKola",
        "id": 31166533,
        "node_id": "MDQ6VXNlcjMxMTY2NTMz",
        "avatar_url": "https://avatars.githubusercontent.com/u/31166533?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CaptainBKola",
        "html_url": "https://github.com/CaptainBKola",
        "followers_url": "https://api.github.com/users/CaptainBKola/followers",
        "following_url": "https://api.github.com/users/CaptainBKola/following{/other_user}",
        "gists_url": "https://api.github.com/users/CaptainBKola/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CaptainBKola/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CaptainBKola/subscriptions",
        "organizations_url": "https://api.github.com/users/CaptainBKola/orgs",
        "repos_url": "https://api.github.com/users/CaptainBKola/repos",
        "events_url": "https://api.github.com/users/CaptainBKola/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CaptainBKola/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "momah95",
        "id": 37146344,
        "node_id": "MDQ6VXNlcjM3MTQ2MzQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/37146344?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/momah95",
        "html_url": "https://github.com/momah95",
        "followers_url": "https://api.github.com/users/momah95/followers",
        "following_url": "https://api.github.com/users/momah95/following{/other_user}",
        "gists_url": "https://api.github.com/users/momah95/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/momah95/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/momah95/subscriptions",
        "organizations_url": "https://api.github.com/users/momah95/orgs",
        "repos_url": "https://api.github.com/users/momah95/repos",
        "events_url": "https://api.github.com/users/momah95/events{/privacy}",
        "received_events_url": "https://api.github.com/users/momah95/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "isholajanet",
        "id": 39619383,
        "node_id": "MDQ6VXNlcjM5NjE5Mzgz",
        "avatar_url": "https://avatars.githubusercontent.com/u/39619383?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/isholajanet",
        "html_url": "https://github.com/isholajanet",
        "followers_url": "https://api.github.com/users/isholajanet/followers",
        "following_url": "https://api.github.com/users/isholajanet/following{/other_user}",
        "gists_url": "https://api.github.com/users/isholajanet/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/isholajanet/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/isholajanet/subscriptions",
        "organizations_url": "https://api.github.com/users/isholajanet/orgs",
        "repos_url": "https://api.github.com/users/isholajanet/repos",
        "events_url": "https://api.github.com/users/isholajanet/events{/privacy}",
        "received_events_url": "https://api.github.com/users/isholajanet/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "Debagboola",
        "id": 40859055,
        "node_id": "MDQ6VXNlcjQwODU5MDU1",
        "avatar_url": "https://avatars.githubusercontent.com/u/40859055?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Debagboola",
        "html_url": "https://github.com/Debagboola",
        "followers_url": "https://api.github.com/users/Debagboola/followers",
        "following_url": "https://api.github.com/users/Debagboola/following{/other_user}",
        "gists_url": "https://api.github.com/users/Debagboola/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Debagboola/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Debagboola/subscriptions",
        "organizations_url": "https://api.github.com/users/Debagboola/orgs",
        "repos_url": "https://api.github.com/users/Debagboola/repos",
        "events_url": "https://api.github.com/users/Debagboola/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Debagboola/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "IbidapoOlalekan",
        "id": 41305811,
        "node_id": "MDQ6VXNlcjQxMzA1ODEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/41305811?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/IbidapoOlalekan",
        "html_url": "https://github.com/IbidapoOlalekan",
        "followers_url": "https://api.github.com/users/IbidapoOlalekan/followers",
        "following_url": "https://api.github.com/users/IbidapoOlalekan/following{/other_user}",
        "gists_url": "https://api.github.com/users/IbidapoOlalekan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/IbidapoOlalekan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/IbidapoOlalekan/subscriptions",
        "organizations_url": "https://api.github.com/users/IbidapoOlalekan/orgs",
        "repos_url": "https://api.github.com/users/IbidapoOlalekan/repos",
        "events_url": "https://api.github.com/users/IbidapoOlalekan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/IbidapoOlalekan/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "tboydv1",
        "id": 45124633,
        "node_id": "MDQ6VXNlcjQ1MTI0NjMz",
        "avatar_url": "https://avatars.githubusercontent.com/u/45124633?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tboydv1",
        "html_url": "https://github.com/tboydv1",
        "followers_url": "https://api.github.com/users/tboydv1/followers",
        "following_url": "https://api.github.com/users/tboydv1/following{/other_user}",
        "gists_url": "https://api.github.com/users/tboydv1/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tboydv1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tboydv1/subscriptions",
        "organizations_url": "https://api.github.com/users/tboydv1/orgs",
        "repos_url": "https://api.github.com/users/tboydv1/repos",
        "events_url": "https://api.github.com/users/tboydv1/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tboydv1/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "Patrick5455",
        "id": 46347439,
        "node_id": "MDQ6VXNlcjQ2MzQ3NDM5",
        "avatar_url": "https://avatars.githubusercontent.com/u/46347439?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Patrick5455",
        "html_url": "https://github.com/Patrick5455",
        "followers_url": "https://api.github.com/users/Patrick5455/followers",
        "following_url": "https://api.github.com/users/Patrick5455/following{/other_user}",
        "gists_url": "https://api.github.com/users/Patrick5455/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Patrick5455/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Patrick5455/subscriptions",
        "organizations_url": "https://api.github.com/users/Patrick5455/orgs",
        "repos_url": "https://api.github.com/users/Patrick5455/repos",
        "events_url": "https://api.github.com/users/Patrick5455/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Patrick5455/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "itunuelijah",
        "id": 46831122,
        "node_id": "MDQ6VXNlcjQ2ODMxMTIy",
        "avatar_url": "https://avatars.githubusercontent.com/u/46831122?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/itunuelijah",
        "html_url": "https://github.com/itunuelijah",
        "followers_url": "https://api.github.com/users/itunuelijah/followers",
        "following_url": "https://api.github.com/users/itunuelijah/following{/other_user}",
        "gists_url": "https://api.github.com/users/itunuelijah/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/itunuelijah/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/itunuelijah/subscriptions",
        "organizations_url": "https://api.github.com/users/itunuelijah/orgs",
        "repos_url": "https://api.github.com/users/itunuelijah/repos",
        "events_url": "https://api.github.com/users/itunuelijah/events{/privacy}",
        "received_events_url": "https://api.github.com/users/itunuelijah/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "akinleries",
        "id": 47524901,
        "node_id": "MDQ6VXNlcjQ3NTI0OTAx",
        "avatar_url": "https://avatars.githubusercontent.com/u/47524901?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/akinleries",
        "html_url": "https://github.com/akinleries",
        "followers_url": "https://api.github.com/users/akinleries/followers",
        "following_url": "https://api.github.com/users/akinleries/following{/other_user}",
        "gists_url": "https://api.github.com/users/akinleries/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/akinleries/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/akinleries/subscriptions",
        "organizations_url": "https://api.github.com/users/akinleries/orgs",
        "repos_url": "https://api.github.com/users/akinleries/repos",
        "events_url": "https://api.github.com/users/akinleries/events{/privacy}",
        "received_events_url": "https://api.github.com/users/akinleries/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "kareemmonsur",
        "id": 47614910,
        "node_id": "MDQ6VXNlcjQ3NjE0OTEw",
        "avatar_url": "https://avatars.githubusercontent.com/u/47614910?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kareemmonsur",
        "html_url": "https://github.com/kareemmonsur",
        "followers_url": "https://api.github.com/users/kareemmonsur/followers",
        "following_url": "https://api.github.com/users/kareemmonsur/following{/other_user}",
        "gists_url": "https://api.github.com/users/kareemmonsur/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kareemmonsur/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kareemmonsur/subscriptions",
        "organizations_url": "https://api.github.com/users/kareemmonsur/orgs",
        "repos_url": "https://api.github.com/users/kareemmonsur/repos",
        "events_url": "https://api.github.com/users/kareemmonsur/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kareemmonsur/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "Akinolae",
        "id": 48059516,
        "node_id": "MDQ6VXNlcjQ4MDU5NTE2",
        "avatar_url": "https://avatars.githubusercontent.com/u/48059516?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Akinolae",
        "html_url": "https://github.com/Akinolae",
        "followers_url": "https://api.github.com/users/Akinolae/followers",
        "following_url": "https://api.github.com/users/Akinolae/following{/other_user}",
        "gists_url": "https://api.github.com/users/Akinolae/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Akinolae/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Akinolae/subscriptions",
        "organizations_url": "https://api.github.com/users/Akinolae/orgs",
        "repos_url": "https://api.github.com/users/Akinolae/repos",
        "events_url": "https://api.github.com/users/Akinolae/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Akinolae/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "dabreeze",
        "id": 48369515,
        "node_id": "MDQ6VXNlcjQ4MzY5NTE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/48369515?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dabreeze",
        "html_url": "https://github.com/dabreeze",
        "followers_url": "https://api.github.com/users/dabreeze/followers",
        "following_url": "https://api.github.com/users/dabreeze/following{/other_user}",
        "gists_url": "https://api.github.com/users/dabreeze/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dabreeze/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dabreeze/subscriptions",
        "organizations_url": "https://api.github.com/users/dabreeze/orgs",
        "repos_url": "https://api.github.com/users/dabreeze/repos",
        "events_url": "https://api.github.com/users/dabreeze/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dabreeze/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "oolabisi",
        "id": 50625324,
        "node_id": "MDQ6VXNlcjUwNjI1MzI0",
        "avatar_url": "https://avatars.githubusercontent.com/u/50625324?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/oolabisi",
        "html_url": "https://github.com/oolabisi",
        "followers_url": "https://api.github.com/users/oolabisi/followers",
        "following_url": "https://api.github.com/users/oolabisi/following{/other_user}",
        "gists_url": "https://api.github.com/users/oolabisi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/oolabisi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/oolabisi/subscriptions",
        "organizations_url": "https://api.github.com/users/oolabisi/orgs",
        "repos_url": "https://api.github.com/users/oolabisi/repos",
        "events_url": "https://api.github.com/users/oolabisi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/oolabisi/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "SimNinwo",
        "id": 50625397,
        "node_id": "MDQ6VXNlcjUwNjI1Mzk3",
        "avatar_url": "https://avatars.githubusercontent.com/u/50625397?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/SimNinwo",
        "html_url": "https://github.com/SimNinwo",
        "followers_url": "https://api.github.com/users/SimNinwo/followers",
        "following_url": "https://api.github.com/users/SimNinwo/following{/other_user}",
        "gists_url": "https://api.github.com/users/SimNinwo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/SimNinwo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/SimNinwo/subscriptions",
        "organizations_url": "https://api.github.com/users/SimNinwo/orgs",
        "repos_url": "https://api.github.com/users/SimNinwo/repos",
        "events_url": "https://api.github.com/users/SimNinwo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/SimNinwo/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "gbemme",
        "id": 50625401,
        "node_id": "MDQ6VXNlcjUwNjI1NDAx",
        "avatar_url": "https://avatars.githubusercontent.com/u/50625401?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gbemme",
        "html_url": "https://github.com/gbemme",
        "followers_url": "https://api.github.com/users/gbemme/followers",
        "following_url": "https://api.github.com/users/gbemme/following{/other_user}",
        "gists_url": "https://api.github.com/users/gbemme/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gbemme/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gbemme/subscriptions",
        "organizations_url": "https://api.github.com/users/gbemme/orgs",
        "repos_url": "https://api.github.com/users/gbemme/repos",
        "events_url": "https://api.github.com/users/gbemme/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gbemme/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "PastorCoder",
        "id": 50626194,
        "node_id": "MDQ6VXNlcjUwNjI2MTk0",
        "avatar_url": "https://avatars.githubusercontent.com/u/50626194?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/PastorCoder",
        "html_url": "https://github.com/PastorCoder",
        "followers_url": "https://api.github.com/users/PastorCoder/followers",
        "following_url": "https://api.github.com/users/PastorCoder/following{/other_user}",
        "gists_url": "https://api.github.com/users/PastorCoder/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/PastorCoder/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/PastorCoder/subscriptions",
        "organizations_url": "https://api.github.com/users/PastorCoder/orgs",
        "repos_url": "https://api.github.com/users/PastorCoder/repos",
        "events_url": "https://api.github.com/users/PastorCoder/events{/privacy}",
        "received_events_url": "https://api.github.com/users/PastorCoder/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "emperorsegxy",
        "id": 51512956,
        "node_id": "MDQ6VXNlcjUxNTEyOTU2",
        "avatar_url": "https://avatars.githubusercontent.com/u/51512956?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/emperorsegxy",
        "html_url": "https://github.com/emperorsegxy",
        "followers_url": "https://api.github.com/users/emperorsegxy/followers",
        "following_url": "https://api.github.com/users/emperorsegxy/following{/other_user}",
        "gists_url": "https://api.github.com/users/emperorsegxy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/emperorsegxy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/emperorsegxy/subscriptions",
        "organizations_url": "https://api.github.com/users/emperorsegxy/orgs",
        "repos_url": "https://api.github.com/users/emperorsegxy/repos",
        "events_url": "https://api.github.com/users/emperorsegxy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/emperorsegxy/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "Oviep",
        "id": 53795498,
        "node_id": "MDQ6VXNlcjUzNzk1NDk4",
        "avatar_url": "https://avatars.githubusercontent.com/u/53795498?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Oviep",
        "html_url": "https://github.com/Oviep",
        "followers_url": "https://api.github.com/users/Oviep/followers",
        "following_url": "https://api.github.com/users/Oviep/following{/other_user}",
        "gists_url": "https://api.github.com/users/Oviep/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Oviep/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Oviep/subscriptions",
        "organizations_url": "https://api.github.com/users/Oviep/orgs",
        "repos_url": "https://api.github.com/users/Oviep/repos",
        "events_url": "https://api.github.com/users/Oviep/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Oviep/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "jerrywise97",
        "id": 54330961,
        "node_id": "MDQ6VXNlcjU0MzMwOTYx",
        "avatar_url": "https://avatars.githubusercontent.com/u/54330961?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jerrywise97",
        "html_url": "https://github.com/jerrywise97",
        "followers_url": "https://api.github.com/users/jerrywise97/followers",
        "following_url": "https://api.github.com/users/jerrywise97/following{/other_user}",
        "gists_url": "https://api.github.com/users/jerrywise97/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jerrywise97/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jerrywise97/subscriptions",
        "organizations_url": "https://api.github.com/users/jerrywise97/orgs",
        "repos_url": "https://api.github.com/users/jerrywise97/repos",
        "events_url": "https://api.github.com/users/jerrywise97/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jerrywise97/received_events",
        "type": "User",
        "site_admin": False
    },
    {
        "login": "dayoolacodes",
        "id": 54889931,
        "node_id": "MDQ6VXNlcjU0ODg5OTMx",
        "avatar_url": "https://avatars.githubusercontent.com/u/54889931?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dayoolacodes",
        "html_url": "https://github.com/dayoolacodes",
        "followers_url": "https://api.github.com/users/dayoolacodes/followers",
        "following_url": "https://api.github.com/users/dayoolacodes/following{/other_user}",
        "gists_url": "https://api.github.com/users/dayoolacodes/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dayoolacodes/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dayoolacodes/subscriptions",
        "organizations_url": "https://api.github.com/users/dayoolacodes/orgs",
        "repos_url": "https://api.github.com/users/dayoolacodes/repos",
        "events_url": "https://api.github.com/users/dayoolacodes/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dayoolacodes/received_events",
        "type": "User",
        "site_admin": False
    }
]

# for i in data:
#    for key, value in i.items():
      # print(key, "->", value)

list_of_odd_id_users = []
list_of_users_with_eight = []
list_of_id_with_eight = []

# def list_of_odd_users():
#    for i in data:
#       if i["id"] % 2 != 0:
#          list_of_odd_id_users.append(i["login"])

# def print_list():
#    for i in list_of_odd_id_users:
#       print(i)
#    print("There are", len(list_of_odd_id_users), "with odd id")
# print()


# def find_users_with_an_eight():
#    for i in data:
#       if str(i["id"]).__contains__('8'):
#          list_of_users_with_eight.append(i["login"])

# def print_list_of_users_with_eight():
#    for i in list_of_users_with_eight:
#       print(i)
#    print("There are", len(list_of_users_with_eight), "with eight")

# def check_user_oviep():
#    for i in data:
#       if i["login"] == "momah95":
#          return i["followers_url"]


# list_of_odd_users()
# print_list()
# find_users_with_an_eight()
# print_list_of_users_with_eight()

# print(check_user_oviep())

# deleting a particular key
# for i in data:
#     for key in list(i.keys()):
#         if key == "id":
#             del i[key]
# print(i)