x = int(0)
print("Number Square Cube")
print(x, (x * x), (x * x * x))
x = int(1)
print(x, (x * x), (x * x * x))
x = int(2)
print(x, (x * x), (x * x * x))
x = int(3)
print(x, (x * x), (x * x * x))
x = int(4)
print(x, (x * x), (x * x * x))
x = int(5)
print(x, (x * x), (x * x * x))
