A = ord('A')
B = ord('B')
C = ord('C')
D = ord('D')
b = ord('i')
c = ord('c')
d = ord('d')
integer_value_of_0 = ord('0')
integer_value_of_1 = ord('1')
integer_value_of_2 = ord('2')
integer_value_of_dollar_sign = ord('$')
integer_value_of_asterisk_sign = ord('*')
integer_value_of_plus_sign = ord('+')
print("The Integer Character value of A is: ", A)
print("The Integer Character value of B is: ", B)
print("The Integer Character value of C is: ", C)
print("The Integer Character value of D is: ", D)
print("The Integer Character value of i is: ", b)
print("The Integer Character value of c is: ", c)
print("The Integer Character value of d is: ", d)
print("The Integer Character value of 0 is: ", integer_value_of_0)
print("The Integer Character value of 1 is: ", integer_value_of_1)
print("The Integer Character value of $ is: ", integer_value_of_dollar_sign)
print("The Integer Character value of * is: ", integer_value_of_asterisk_sign)
print("The Integer Character value of + is: ", integer_value_of_plus_sign)