print("The integer value of character 'B' is", end=": ")
print(ord('B'))
print("The integer value of character 'C' is", end=": ")
print(ord('C'))
print("The integer value of character 'D' is", end=": ")
print(ord('D'))
print("The integer value of character 'i' is", end=": ")
print(ord('i'))
print("The integer value of character 'c' is", end=": ")
print(ord('c'))
print("The integer value of character 'd' is", end=": ")
print(ord('d'))
print("The integer value of character '0' is", end=": ")
print(ord('0'))
print("The integer value of character '1' is", end=": ")
print(ord('1'))
print("The integer value of character '2' is", end=": ")
print(ord('2'))
print("The integer value of character '$' is", end=": ")
print(ord('$'))
print("The integer value of character '*' is", end=": ")
print(ord('*'))
print("The integer value of character '+' is", end=": ")
print(ord('+'))
print("The integer value of character ' ' is", end=": ")
print(ord(' '))
